# Generated by Django 3.1.5 on 2021-04-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adt',
            fields=[
                ('id_adt', models.IntegerField(primary_key=True, serialize=False)),
                ('name_adt', models.CharField(default='', max_length=256)),
                ('adt_border', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.IntegerField(primary_key=True, serialize=False)),
                ('name_country', models.CharField(default='', max_length=256)),
                ('country_border', models.CharField(default='', max_length=256)),
                ('id_adt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.adt')),
            ],
        ),
        migrations.CreateModel(
            name='Data_oper_codes',
            fields=[
                ('id_data_oper_codes', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(default=None)),
                ('shortnamecode', models.CharField(default='', max_length=256)),
                ('fullnamecode', models.CharField(default='', max_length=256)),
                ('national_code_number', models.CharField(default='', max_length=256)),
                ('name_in_document', models.CharField(default='', max_length=256)),
                ('year_publication', models.IntegerField(default=None)),
                ('data_start', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Fed_o',
            fields=[
                ('id_fed_o', models.IntegerField(primary_key=True, serialize=False)),
                ('name_fed_o', models.CharField(default='', max_length=256)),
                ('fed_o_border', models.CharField(default='', max_length=256)),
                ('id_adt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.adt')),
                ('id_country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.country')),
            ],
        ),
        migrations.CreateModel(
            name='Subrf',
            fields=[
                ('id_subrf', models.IntegerField(primary_key=True, serialize=False)),
                ('name_subrf', models.CharField(default='', max_length=256)),
                ('subrf_border', models.CharField(default='', max_length=256)),
                ('id_adt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.adt')),
                ('id_country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.country')),
                ('id_fed_o', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.fed_o')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id_station', models.IntegerField(primary_key=True, serialize=False)),
                ('station_index', models.IntegerField(default=None)),
                ('name_station_rus', models.CharField(default='', max_length=256)),
                ('name_station_en', models.CharField(default='', max_length=256)),
                ('latitude', models.CharField(default='', max_length=256)),
                ('longitude', models.CharField(default='', max_length=256)),
                ('height_above_sea', models.CharField(default='', max_length=256)),
                ('access_level', models.CharField(default='', max_length=256)),
                ('id_adt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.adt')),
                ('id_country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.country')),
                ('id_subrf', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.subrf')),
            ],
        ),
        migrations.CreateModel(
            name='Ugms',
            fields=[
                ('id_ugms', models.IntegerField(primary_key=True, serialize=False)),
                ('name_ugms', models.CharField(default='', max_length=256)),
                ('ugms_border', models.CharField(default='', max_length=256)),
                ('id_adt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.adt')),
                ('id_country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.country')),
                ('id_subrf', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.subrf')),
            ],
        ),
        migrations.CreateModel(
            name='Econfields',
            fields=[
                ('id_econfields', models.IntegerField(primary_key=True, serialize=False)),
                ('name_econfields', models.CharField(default='', max_length=256)),
                ('econfields_border', models.CharField(default='', max_length=256)),
                ('id_adt', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.adt')),
                ('id_country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.country')),
            ],
        ),
        migrations.CreateModel(
            name='ClimatData',
            fields=[
                ('id_climatdata', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp_record', models.CharField(default='', max_length=256)),
                ('tflag', models.CharField(default='', max_length=256)),
                ('temperature', models.CharField(default='', max_length=256)),
                ('pressure_stlev', models.CharField(default='', max_length=256)),
                ('wind_direction', models.CharField(default='', max_length=256)),
                ('average_wind_speed', models.CharField(default='', max_length=256)),
                ('horizontal_vizibility', models.CharField(default='', max_length=256)),
                ('clouds_height', models.CharField(default='', max_length=256)),
                ('clouds_number', models.CharField(default='', max_length=256)),
                ('special_phenomena', models.CharField(default='', max_length=256)),
                ('id_station', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.weatherstation')),
            ],
        ),
    ]
