# Generated by Django 3.1.5 on 2021-04-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obsnet', '0006_auto_20210414_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adt',
            name='id_country',
        ),
        migrations.RemoveField(
            model_name='econfields',
            name='id_country',
        ),
        migrations.RemoveField(
            model_name='fed_o',
            name='id_country',
        ),
        migrations.RemoveField(
            model_name='ugms',
            name='id_adt',
        ),
        migrations.RemoveField(
            model_name='ugms',
            name='id_country',
        ),
        migrations.RemoveField(
            model_name='ugms',
            name='id_subrf',
        ),
        migrations.RemoveField(
            model_name='weatherstation',
            name='id_subrf',
        ),
    ]
