# Generated by Django 3.1.5 on 2021-04-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsnet', '0007_auto_20210414_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ugms',
            name='ugms_border',
        ),
        migrations.AddField(
            model_name='econfields',
            name='id_country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.country'),
        ),
        migrations.AddField(
            model_name='fed_o',
            name='id_country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.country'),
        ),
        migrations.AddField(
            model_name='subrf',
            name='id_country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.country'),
        ),
        migrations.AddField(
            model_name='ugms',
            name='id_subrf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.subrf'),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='id_country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.country'),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='id_subrf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.subrf'),
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='id_ugms',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='obsnet.ugms'),
        ),
    ]
