# Generated by Django 3.1.5 on 2021-05-18 10:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsnet', '0008_auto_20210415_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oblasti',
            fields=[
                ('id_oblasti', models.IntegerField(primary_key=True, serialize=False)),
                ('name_oblasti', models.CharField(default='', max_length=256)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
